/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 2.28.0
 */

package com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.batch;

import com.sap.cloud.sdk.s4hana.datamodel.odata.helper.batch.FluentHelperServiceBatch;


/**
 * Interface to the batch object of an {@code com.sap.cloud.sdk.s4hana.datamodel.odata.services.MeataService MeataService} service.
 * 
 */
public interface MeataServiceBatch
    extends FluentHelperServiceBatch<MeataServiceBatch, MeataServiceBatchChangeSet>
{


}
