/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 2.28.0
 */

package com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.selectable;

import com.sap.cloud.sdk.s4hana.datamodel.odata.helper.EntitySelectable;
import com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Pilot;


/**
 * Interface to enable OData entity selectors for {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Pilot Pilot}. This interface is used by {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.field.PilotField PilotField} and {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.link.PilotLink PilotLink}.
 * 
 * <p>Available instances:
 * <ul>
 * <li>{@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Pilot#MODIFIED_AT MODIFIED_AT}</li>
 * <li>{@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Pilot#CREATED_AT CREATED_AT}</li>
 * <li>{@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Pilot#CREATED_BY CREATED_BY}</li>
 * <li>{@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Pilot#MODIFIED_BY MODIFIED_BY}</li>
 * <li>{@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Pilot#ID ID}</li>
 * <li>{@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Pilot#NAME NAME}</li>
 * <li>{@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Pilot#DATE_OF_BIRTH DATE_OF_BIRTH}</li>
 * <li>{@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Pilot#PLACE_OF_BIRTH PLACE_OF_BIRTH}</li>
 * </ul>
 * 
 */
public interface PilotSelectable
    extends EntitySelectable<Pilot>
{


}
