/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 2.28.0
 */

package com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata;

import java.util.Map;
import javax.annotation.Nonnull;
import com.google.common.collect.Maps;
import com.sap.cloud.sdk.s4hana.datamodel.odata.helper.FluentHelperByKey;
import com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.selectable.PlaneSelectable;


/**
 * Fluent helper to fetch a single {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane Plane} entity using key fields. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. 
 * 
 */
public class PlaneByKeyFluentHelper
    extends FluentHelperByKey<PlaneByKeyFluentHelper, Plane, PlaneSelectable>
{

    private final Map<String, Object> key = Maps.newHashMap();

    /**
     * Creates a fluent helper object that will fetch a single {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane Plane} entity with the provided key field values. To perform execution, call the {@link #execute execute} method on the fluent helper object.
     * 
     * @param servicePath
     *     Service path to be used to fetch a single {@code Plane}
     * @param iD
     *     
     */
    public PlaneByKeyFluentHelper(
        @Nonnull
        final String servicePath, final Integer iD) {
        super(servicePath);
        this.key.put("ID", iD);
    }

    @Override
    @Nonnull
    protected Class<Plane> getEntityClass() {
        return Plane.class;
    }

    @Override
    @Nonnull
    protected Map<String, Object> getKey() {
        return key;
    }

}
