/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 2.28.0
 */

package com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.link;

import javax.annotation.Nonnull;
import com.sap.cloud.sdk.s4hana.datamodel.odata.helper.EntityLink;
import com.sap.cloud.sdk.s4hana.datamodel.odata.helper.VdmObject;
import com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane;
import com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.selectable.PlaneSelectable;


/**
 * Template class to represent entity navigation links of {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane Plane} to other entities. Instances of this object are used in query modifier methods of the entity
 * fluent helpers. Contains methods to compare a field's value with a provided value.
 * 
 * Use the constants declared in each entity inner class. Instantiating directly requires knowing the underlying OData
 * field names, so use the constructor with caution.
 * 
 * @param <ObjectT>
 * Entity type of subclasses from {@link com.sap.cloud.sdk.s4hana.datamodel.odata.helper.VdmObject VdmObject}.
 * 
 */
public class PlaneLink<ObjectT extends VdmObject<?> >
    extends EntityLink<PlaneLink<ObjectT> , Plane, ObjectT>
    implements PlaneSelectable
{


    /**
     * Use the constants declared in each entity inner class. Instantiating directly requires knowing the underlying OData field names, so use with caution.
     * 
     * @param fieldName
     *     OData navigation field name. Must match the field returned by the underlying OData service.
     */
    public PlaneLink(final String fieldName) {
        super(fieldName);
    }

    private PlaneLink(final EntityLink<PlaneLink<ObjectT> , Plane, ObjectT> toClone) {
        super(toClone);
    }

    @Nonnull
    @Override
    protected PlaneLink<ObjectT> translateLinkType(final EntityLink<PlaneLink<ObjectT> , Plane, ObjectT> link) {
        return new PlaneLink<ObjectT>(link);
    }

}
