/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 2.28.0
 */

package com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.link;

import javax.annotation.Nonnull;
import com.sap.cloud.sdk.s4hana.datamodel.odata.helper.EntityLink;
import com.sap.cloud.sdk.s4hana.datamodel.odata.helper.VdmObject;
import com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Pilot;
import com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.selectable.PilotSelectable;


/**
 * Template class to represent entity navigation links of {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Pilot Pilot} to other entities. Instances of this object are used in query modifier methods of the entity
 * fluent helpers. Contains methods to compare a field's value with a provided value.
 * 
 * Use the constants declared in each entity inner class. Instantiating directly requires knowing the underlying OData
 * field names, so use the constructor with caution.
 * 
 * @param <ObjectT>
 * Entity type of subclasses from {@link com.sap.cloud.sdk.s4hana.datamodel.odata.helper.VdmObject VdmObject}.
 * 
 */
public class PilotLink<ObjectT extends VdmObject<?> >
    extends EntityLink<PilotLink<ObjectT> , Pilot, ObjectT>
    implements PilotSelectable
{


    /**
     * Use the constants declared in each entity inner class. Instantiating directly requires knowing the underlying OData field names, so use with caution.
     * 
     * @param fieldName
     *     OData navigation field name. Must match the field returned by the underlying OData service.
     */
    public PilotLink(final String fieldName) {
        super(fieldName);
    }

    private PilotLink(final EntityLink<PilotLink<ObjectT> , Pilot, ObjectT> toClone) {
        super(toClone);
    }

    @Nonnull
    @Override
    protected PilotLink<ObjectT> translateLinkType(final EntityLink<PilotLink<ObjectT> , Pilot, ObjectT> link) {
        return new PilotLink<ObjectT>(link);
    }

}
