/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 2.28.0
 */

package com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.selectable;

import com.sap.cloud.sdk.s4hana.datamodel.odata.helper.EntitySelectable;
import com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane_texts;


/**
 * Interface to enable OData entity selectors for {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane_texts Plane_texts}. This interface is used by {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.field.Plane_textsField Plane_textsField} and {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.link.Plane_textsLink Plane_textsLink}.
 * 
 * <p>Available instances:
 * <ul>
 * <li>{@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane_texts#LOCALE LOCALE}</li>
 * <li>{@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane_texts#ID ID}</li>
 * <li>{@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane_texts#DESCR DESCR}</li>
 * </ul>
 * 
 */
public interface Plane_textsSelectable
    extends EntitySelectable<Plane_texts>
{


}
