/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 2.28.0
 */

package com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.selectable;

import com.sap.cloud.sdk.s4hana.datamodel.odata.helper.EntitySelectable;
import com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane;


/**
 * Interface to enable OData entity selectors for {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane Plane}. This interface is used by {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.field.PlaneField PlaneField} and {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.link.PlaneLink PlaneLink}.
 * 
 * <p>Available instances:
 * <ul>
 * <li>{@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane#MODIFIED_AT MODIFIED_AT}</li>
 * <li>{@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane#CREATED_AT CREATED_AT}</li>
 * <li>{@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane#CREATED_BY CREATED_BY}</li>
 * <li>{@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane#MODIFIED_BY MODIFIED_BY}</li>
 * <li>{@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane#ID ID}</li>
 * <li>{@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane#DESCR DESCR}</li>
 * <li>{@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane#TO_TEXTS TO_TEXTS}</li>
 * <li>{@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane#TO_LOCALIZED TO_LOCALIZED}</li>
 * </ul>
 * 
 */
public interface PlaneSelectable
    extends EntitySelectable<Plane>
{


}
