/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 2.28.0
 */

package com.sap.cloud.sdk.s4hana.datamodel.odata.services;

import javax.annotation.Nonnull;
import com.sap.cloud.sdk.s4hana.datamodel.odata.helper.batch.BatchService;
import com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Pilot;
import com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.PilotByKeyFluentHelper;
import com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.PilotCreateFluentHelper;
import com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.PilotDeleteFluentHelper;
import com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.PilotFluentHelper;
import com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.PilotUpdateFluentHelper;
import com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane;
import com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.PlaneByKeyFluentHelper;
import com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.PlaneCreateFluentHelper;
import com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.PlaneDeleteFluentHelper;
import com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.PlaneFluentHelper;
import com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.PlaneUpdateFluentHelper;
import com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane_texts;
import com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane_textsByKeyFluentHelper;
import com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane_textsCreateFluentHelper;
import com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane_textsDeleteFluentHelper;
import com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane_textsFluentHelper;
import com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane_textsUpdateFluentHelper;
import com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.batch.MeataServiceBatch;


/**
 * <h3>Details:</h3><table summary='Details'><tr><td align='right'>OData Service:</td><td>meata</td></tr></table>
 * 
 */
public interface MeataService
    extends BatchService<MeataServiceBatch>
{

    /**
     * If no other path was provided via the {@link #withServicePath(String)} method, this is the default service path used to access the endpoint.
     * 
     */
    String DEFAULT_SERVICE_PATH = "/odata/v2/CatalogService";

    /**
     * Overrides the default service path and returns a new service instance with the specified service path. Also adjusts the respective entity URLs.
     * 
     * @param servicePath
     *     Service path that will override the default.
     * @return
     *     A new service instance with the specified service path.
     */
    @Nonnull
    MeataService withServicePath(
        @Nonnull
        final String servicePath);

    /**
     * Fetch multiple {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Pilot Pilot} entities.
     * 
     * @return
     *     A fluent helper to fetch multiple {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Pilot Pilot} entities. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.PilotFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    PilotFluentHelper getAllPilot();

    /**
     * Fetch a single {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Pilot Pilot} entity using key fields.
     * 
     * @param iD
     *     
     * @return
     *     A fluent helper to fetch a single {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Pilot Pilot} entity using key fields. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.PilotByKeyFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    PilotByKeyFluentHelper getPilotByKey(final Integer iD);

    /**
     * Create a new {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Pilot Pilot} entity and save it to the S/4HANA system.
     * 
     * @param pilot
     *     {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Pilot Pilot} entity object that will be created in the S/4HANA system.
     * @return
     *     A fluent helper to create a new {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Pilot Pilot} entity. To perform execution, call the {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.PilotCreateFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    PilotCreateFluentHelper createPilot(
        @Nonnull
        final Pilot pilot);

    /**
     * Update an existing {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Pilot Pilot} entity and save it to the S/4HANA system.
     * 
     * @param pilot
     *     {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Pilot Pilot} entity object that will be updated in the S/4HANA system.
     * @return
     *     A fluent helper to update an existing {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Pilot Pilot} entity. To perform execution, call the {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.PilotUpdateFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    PilotUpdateFluentHelper updatePilot(
        @Nonnull
        final Pilot pilot);

    /**
     * Deletes an existing {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Pilot Pilot} entity in the S/4HANA system.
     * 
     * @param pilot
     *     {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Pilot Pilot} entity object that will be deleted in the S/4HANA system.
     * @return
     *     A fluent helper to delete an existing {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Pilot Pilot} entity. To perform execution, call the {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.PilotDeleteFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    PilotDeleteFluentHelper deletePilot(
        @Nonnull
        final Pilot pilot);

    /**
     * Fetch multiple {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane Plane} entities.
     * 
     * @return
     *     A fluent helper to fetch multiple {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane Plane} entities. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.PlaneFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    PlaneFluentHelper getAllPlane();

    /**
     * Fetch a single {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane Plane} entity using key fields.
     * 
     * @param iD
     *     
     * @return
     *     A fluent helper to fetch a single {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane Plane} entity using key fields. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.PlaneByKeyFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    PlaneByKeyFluentHelper getPlaneByKey(final Integer iD);

    /**
     * Create a new {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane Plane} entity and save it to the S/4HANA system.
     * 
     * @param plane
     *     {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane Plane} entity object that will be created in the S/4HANA system.
     * @return
     *     A fluent helper to create a new {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane Plane} entity. To perform execution, call the {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.PlaneCreateFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    PlaneCreateFluentHelper createPlane(
        @Nonnull
        final Plane plane);

    /**
     * Update an existing {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane Plane} entity and save it to the S/4HANA system.
     * 
     * @param plane
     *     {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane Plane} entity object that will be updated in the S/4HANA system.
     * @return
     *     A fluent helper to update an existing {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane Plane} entity. To perform execution, call the {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.PlaneUpdateFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    PlaneUpdateFluentHelper updatePlane(
        @Nonnull
        final Plane plane);

    /**
     * Deletes an existing {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane Plane} entity in the S/4HANA system.
     * 
     * @param plane
     *     {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane Plane} entity object that will be deleted in the S/4HANA system.
     * @return
     *     A fluent helper to delete an existing {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane Plane} entity. To perform execution, call the {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.PlaneDeleteFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    PlaneDeleteFluentHelper deletePlane(
        @Nonnull
        final Plane plane);

    /**
     * Fetch multiple {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane_texts Plane_texts} entities.
     * 
     * @return
     *     A fluent helper to fetch multiple {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane_texts Plane_texts} entities. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane_textsFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    Plane_textsFluentHelper getAllPlane_texts();

    /**
     * Fetch a single {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane_texts Plane_texts} entity using key fields.
     * 
     * @param iD
     *     
     * @param locale
     *     
     * @return
     *     A fluent helper to fetch a single {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane_texts Plane_texts} entity using key fields. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane_textsByKeyFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    Plane_textsByKeyFluentHelper getPlane_textsByKey(final String locale, final Integer iD);

    /**
     * Create a new {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane_texts Plane_texts} entity and save it to the S/4HANA system.
     * 
     * @param plane_texts
     *     {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane_texts Plane_texts} entity object that will be created in the S/4HANA system.
     * @return
     *     A fluent helper to create a new {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane_texts Plane_texts} entity. To perform execution, call the {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane_textsCreateFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    Plane_textsCreateFluentHelper createPlane_texts(
        @Nonnull
        final Plane_texts plane_texts);

    /**
     * Update an existing {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane_texts Plane_texts} entity and save it to the S/4HANA system.
     * 
     * @param plane_texts
     *     {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane_texts Plane_texts} entity object that will be updated in the S/4HANA system.
     * @return
     *     A fluent helper to update an existing {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane_texts Plane_texts} entity. To perform execution, call the {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane_textsUpdateFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    Plane_textsUpdateFluentHelper updatePlane_texts(
        @Nonnull
        final Plane_texts plane_texts);

    /**
     * Deletes an existing {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane_texts Plane_texts} entity in the S/4HANA system.
     * 
     * @param plane_texts
     *     {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane_texts Plane_texts} entity object that will be deleted in the S/4HANA system.
     * @return
     *     A fluent helper to delete an existing {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane_texts Plane_texts} entity. To perform execution, call the {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane_textsDeleteFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    Plane_textsDeleteFluentHelper deletePlane_texts(
        @Nonnull
        final Plane_texts plane_texts);

}
