/*
 * Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 2.28.0
 */

package com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.batch;

import javax.annotation.Nonnull;
import com.sap.cloud.sdk.s4hana.datamodel.odata.helper.batch.FluentHelperBatchEndChangeSet;
import com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Pilot;
import com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane;
import com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane_texts;


/**
 * This interface enables you to combine multiple operations into one change set. For further information have a look into the {@link com.sap.cloud.sdk.s4hana.datamodel.odata.services.MeataService MeataService}.
 * 
 */
public interface MeataServiceBatchChangeSet
    extends FluentHelperBatchEndChangeSet<MeataServiceBatch>
{


    /**
     * Create a new {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Pilot Pilot} entity and save it to the S/4HANA system.
     * 
     * @param pilot
     *     {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Pilot Pilot} entity object that will be created in the S/4HANA system.
     * @return
     *     This fluent helper to continue adding operations to the change set. To finalize the current change set call {@link #endChangeSet endChangeSet} on the returned fluent helper object.
     */
    @Nonnull
    MeataServiceBatchChangeSet createPilot(
        @Nonnull
        final Pilot pilot);

    /**
     * Update an existing {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Pilot Pilot} entity and save it to the S/4HANA system.
     * 
     * @param pilot
     *     {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Pilot Pilot} entity object that will be updated in the S/4HANA system.
     * @return
     *     This fluent helper to continue adding operations to the change set. To finalize the current change set call {@link #endChangeSet endChangeSet} on the returned fluent helper object.
     */
    @Nonnull
    MeataServiceBatchChangeSet updatePilot(
        @Nonnull
        final Pilot pilot);

    /**
     * Deletes an existing {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Pilot Pilot} entity in the S/4HANA system.
     * 
     * @param pilot
     *     {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Pilot Pilot} entity object that will be deleted in the S/4HANA system.
     * @return
     *     This fluent helper to continue adding operations to the change set. To finalize the current change set call {@link #endChangeSet endChangeSet} on the returned fluent helper object.
     */
    @Nonnull
    MeataServiceBatchChangeSet deletePilot(
        @Nonnull
        final Pilot pilot);

    /**
     * Create a new {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane Plane} entity and save it to the S/4HANA system.
     * 
     * @param plane
     *     {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane Plane} entity object that will be created in the S/4HANA system.
     * @return
     *     This fluent helper to continue adding operations to the change set. To finalize the current change set call {@link #endChangeSet endChangeSet} on the returned fluent helper object.
     */
    @Nonnull
    MeataServiceBatchChangeSet createPlane(
        @Nonnull
        final Plane plane);

    /**
     * Update an existing {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane Plane} entity and save it to the S/4HANA system.
     * 
     * @param plane
     *     {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane Plane} entity object that will be updated in the S/4HANA system.
     * @return
     *     This fluent helper to continue adding operations to the change set. To finalize the current change set call {@link #endChangeSet endChangeSet} on the returned fluent helper object.
     */
    @Nonnull
    MeataServiceBatchChangeSet updatePlane(
        @Nonnull
        final Plane plane);

    /**
     * Deletes an existing {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane Plane} entity in the S/4HANA system.
     * 
     * @param plane
     *     {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane Plane} entity object that will be deleted in the S/4HANA system.
     * @return
     *     This fluent helper to continue adding operations to the change set. To finalize the current change set call {@link #endChangeSet endChangeSet} on the returned fluent helper object.
     */
    @Nonnull
    MeataServiceBatchChangeSet deletePlane(
        @Nonnull
        final Plane plane);

    /**
     * Create a new {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane_texts Plane_texts} entity and save it to the S/4HANA system.
     * 
     * @param plane_texts
     *     {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane_texts Plane_texts} entity object that will be created in the S/4HANA system.
     * @return
     *     This fluent helper to continue adding operations to the change set. To finalize the current change set call {@link #endChangeSet endChangeSet} on the returned fluent helper object.
     */
    @Nonnull
    MeataServiceBatchChangeSet createPlane_texts(
        @Nonnull
        final Plane_texts plane_texts);

    /**
     * Update an existing {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane_texts Plane_texts} entity and save it to the S/4HANA system.
     * 
     * @param plane_texts
     *     {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane_texts Plane_texts} entity object that will be updated in the S/4HANA system.
     * @return
     *     This fluent helper to continue adding operations to the change set. To finalize the current change set call {@link #endChangeSet endChangeSet} on the returned fluent helper object.
     */
    @Nonnull
    MeataServiceBatchChangeSet updatePlane_texts(
        @Nonnull
        final Plane_texts plane_texts);

    /**
     * Deletes an existing {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane_texts Plane_texts} entity in the S/4HANA system.
     * 
     * @param plane_texts
     *     {@link com.sap.cloud.sdk.s4hana.datamodel.odata.namespaces.meata.Plane_texts Plane_texts} entity object that will be deleted in the S/4HANA system.
     * @return
     *     This fluent helper to continue adding operations to the change set. To finalize the current change set call {@link #endChangeSet endChangeSet} on the returned fluent helper object.
     */
    @Nonnull
    MeataServiceBatchChangeSet deletePlane_texts(
        @Nonnull
        final Plane_texts plane_texts);

}
